### ISSUE TITLE
Could not pass event AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by dylanhansch** [dylanhansch/Lavahub#15]
Note to self. Receiving this error in console running on a Spigot 1.9.4 server.

```
[16:20:41] [Async Chat Thread - #0/ERROR]: Could not pass event AsyncPlayerChatEvent to Lavahub v1.0-SNAPSHOT
org.bukkit.event.EventException
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerConnection.chat(PlayerConnection.java:1271) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1209) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at net.minecraft.server.v1_9_R2.PacketPlayInChat$1.run(PacketPlayInChat.java:39) [spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_91]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_91]
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
	at net.dylanhansch.lavahub.Lavahub.onPlayerChat(Lavahub.java:90) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_91]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_91]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot-1.9.4.jar:git-Spigot-4af49dc-c5e9a16]
	... 11 more
```

**Comment by dylanhansch** [comment]
Fixed in recent commit 114ea55b0bbcc2fe10f81f7d6ec2175b95b80b57
